<!--Autor: Florian Baumann, Version 2, Userstory: Als Mitarbeiter möchte ich auch über meinen Browser, meine Arbeitsstunden einsehen können; Tabelle für PHP-->

<!--Session Start und Anbindung an den header-->
<?php
include('header.php');
?>
<!-- Hier kann die Seite mit Inhalt gefüllt werden -->
<tr >
<td>
<br>
<p>Bitte tragen Sie ihre Arbeitszeiten in der unten gezeigten Tabelle ein. Der Arbeitsplan kann dann von der Personalabteilung generiert werden.</p>
<table border ="1" width="70%" >
<tr>
    <th width="12.5%"></th>
    <th width="12.5%">Montag</th>
    <th width="12.5%">Dienstag</th>
	<th width="12.5%">Mittwoch</th>
	<th width="12.5%">Donnerstag</th>
	<th width="12.5%">Freitag</th>
	<th width="12.5%">Samstag</th>
	<th width="12.5%">Sonntag</th>
  </tr>
  <tr>
    <td>00:00<br>-<br>01:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
  <tr>
   <td>01:00<br>-<br>02:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>02:00<br>-<br>03:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>03:00<br>-<br>04:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>04:00<br>-<br>05:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>05:00<br>-<br>06:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>06:00<br>-<br>07:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>07:00<br>-<br>08:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>08:00<br>-<br>09:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>09:00<br>-<br>10:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>10:00<br>-<br>11:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>11:00<br>-<br>12:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>12:00<br>-<br>13:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>13:00<br>-<br>14:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>14:00<br>-<br>15:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>15:00<br>-<br>16:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>16:00<br>-<br>17:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>17:00<br>-<br>18:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>18:00<br>-<br>19:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>19:00<br>-<br>20:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>20:00<br>-<br>21:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>21:00<br>-<br>22:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>22:00<br>-<br>23:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
   <tr>
   <td>23:00<br>-<br>24:00</td>
    <td></td>
    <td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
 
</table>
</td>
</tr>

</body>
</html>